# Copyright Justin R. Goheen.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

model: ".models/llama-3.2-1b-instruct-q4_k_m.gguf"

evaluations:
  human: true
  judge: true
  rag: true
  tasks: true

human:
  kwarg: value

judge:
  answer_relevancy: {setting: value}
  contextual_relevancy: {setting: value}
  groundedness: {setting: value}

rag:
  retriever: "similarity"
  embed_model: "model_name"
  reranker: "model_name"

tasks:
  - mmlu
  - hellaswag
  - gsm8k
